<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="MudBlazor" Version="9.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Application\CO.Application\CO.Application.csproj" />
    <ProjectReference Include="..\..\Infrastructure\CO.Infrastructure\CO.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Persistence\CO.Persistence\CO.Persistence.csproj" />
    <ProjectReference Include="..\..\Shared\CO.Shared.Validation\CO.Shared.Validation.csproj" />
    <ProjectReference Include="..\..\Shared\CO.Shared\CO.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\Dashboard\Components\" />
    <Folder Include="Features\Dashboard\Models\" />
    <Folder Include="Features\Dashboard\Pages\" />
  </ItemGroup>

</Project>
